name: Run main.py and commit changes

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install dependencies using Poetry
      run: poetry install

    - name: Fetch latest data
      run: poetry run python main.py
      env:
        MEDIAWIKI_ACCESS_TOKEN: ${{ secrets.MEDIAWIKI_ACCESS_TOKEN }}

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
