name: Run main.py and commit changes

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: write

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: .venv
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    - name: Fetch latest data
      run: poetry run python main.py
      env:
        MEDIAWIKI_ACCESS_TOKEN: ${{ secrets.MEDIAWIKI_ACCESS_TOKEN }}

    - name: Commit and push if it changed
      run: |-
        git config --global user.name "Automated"
        git config --global user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push

    - name: Install Git LFS
      run: |-
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install

    - name: Push data to Hugging Face
      if: ${{ env.HF_TOKEN != '' }}
      run: |-
        git clone https://user:${HF_TOKEN}@huggingface.co/datasets/vtasca/wikipedia-pageviews hf_repo
        cd hf_repo

        git lfs track "pageviews.csv"
        git add .gitattributes || true

        cp ../pageviews.csv .
        git add pageviews.csv
        git commit -m "Latest data: $(date -u)" || exit 0

        git push origin main
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
